---

language: bash

env:
  - BASH=latest
  - BASH=5.0.3
  - BASH=4.4.23
  - BASH=4.3.48
  - BASH=4.2.53

before_script:
  - git clone https://github.com/bats-core/bats-core.git vendor/bats-core
  - git clone https://github.com/ztombol/bats-support vendor/bats-support
  - git clone https://github.com/ztombol/bats-assert vendor/bats-assert
  - docker pull bash:$BASH
  - docker run bash:$BASH --version

script:
  - docker run -it -w /bash -v "$PWD":/bash:ro bash:$BASH bin/run_tests
